# Generated by Django 5.2 on 2025-04-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('studentName', models.CharField(max_length=100)),
                ('physics', models.IntegerField()),
                ('chemistry', models.IntegerField()),
                ('math', models.IntegerField()),
            ],
        ),
    ]
