# Generated by Django 5.2 on 2025-04-09 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='Teachers',
        ),
    ]
