# Generated by Django 5.2 on 2025-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_exam1_delete_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=100)),
                ('teacher_mobile', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Exam1',
        ),
    ]
