# Generated by Django 5.2 on 2025-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_contacts_delete_exam1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
